[profile.default]
src = "src"
out = "out"
libs = ["lib"]
auto_detect_remappings = false

# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options
[rpc_endpoints]
testnet = "https://testnet-rpc.monad.xyz"
